name: macos

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - macos-10.15
        - macos-11.0
        ruby: [ '2.6', '2.7', '3.0', '3.1', 'debug', 'head' ]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Run test
      run: bundle exec rake
