name: macos

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
        - macos-11.0
        ruby: [ '2.7', '3.0', '3.1', '3.2', 'debug', 'head' ]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Compile
      run: bundle exec rake compile
    - name: Build gem
      run: bundle exec rake build
    - uses: actions/upload-artifact@v3
      if: >-
        matrix.os == 'ubuntu-22.04' &&
          matrix.ruby == '3.2'
      with:
        name: gem-${{ matrix.os }}-${{ matrix.ruby }}
        path: pkg/
      id: upload
    - uses: softprops/action-gh-release@v1
      if: steps.upload.outcome == 'success'
      with:
        files: |
          pkg/*.gem
    - name: Run test
      run: bundle exec rake
