name: Release
on:
  push:
    tags:
      - "*"
jobs:
  github:
    name: GitHub
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Make a release note
        id: note
        run: |
          #!ruby
          note = File.read("NEWS.md")[/^## (.*)\n++\K(?m:.*?)(?=\n## |\z)/]
          version = $1
          File.write("release-note.md", note)
          File.write(ENV['GITHUB_OUTPUT'], "title=stringio #{version}", mode: "a")
        shell: ruby {0}
      - name: Create a release
        run: >-
          gh release create ${GITHUB_REF_NAME}
          --discussion-category Announcements
          --notes-file release-note-without-version.md
          --title "${{ github.steps.note.outputs.title }}"
        env:
          GH_TOKEN: ${{ github.token }}
